
GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/1

###

POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Electronics"
}

###


PUT http://localhost:3000/categories/1
Content-Type: application/json

{
  "name": "Updated Electronics"
}

###

DELETE http://localhost:3000/categories/1
