
GET http://localhost:3000/tags

###

GET http://localhost:3000/tags/1

###

POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "Smartphone"
}

###

PUT http://localhost:3000/tags/1
Content-Type: application/json

{
  "name": "Updated Smartphone"
}

###

### Delete a tag
DELETE http://localhost:3000/tags/1
