
GET http://localhost:3000/tags

###

GET http://localhost:3000/tags/1

###

POST http://localhost:3000/tags
Content-Type: application/json

{
  "title": "Smartphone"
}

###

PUT http://localhost:3000/tags/1
Content-Type: application/json

{
  "title": "Updated Smartphone"
}

###

DELETE http://localhost:3000/tags/1
